In [16]:
import numpy as np
tgt = np.array([3, 5, 8, 10, 12, 15])
num_guesses = 10
results = []
for g in range(num_guesses):
  guess = np.random.uniform(low=tgt.min(), high=tgt.max())
  print(guess)
  total_dist = np.sum((tgt - guess)**2)
  print(tgt)
  print(total_dist)
  results.append((total_dist, guess))
best_guess = sorted(results)[0][1]
print("_____________")
print(best_guess)

13.843370699014823
[ 3  5  8 10 12 15]
249.4361797664817
3.679728032954823
[ 3  5  8 10 12 15]
258.19121888587017
13.395189863776253
[ 3  5  8 10 12 15]
223.69654335940163
11.453497604027785
[ 3  5  8 10 12 15]
140.02489816587604
3.8522711031087975
[ 3  5  8 10 12 15]
247.69921898154985
9.0914865276836
[ 3  5  8 10 12 15]
99.2331917638528
12.937152076883624
[ 3  5  8 10 12 15]
199.88130301282146
14.631847606057264
[ 3  5  8 10 12 15]
300.5699399592321
12.852346347725549
[ 3  5  8 10 12 15]
195.74812699245734
11.052410263899802
[ 3  5  8 10 12 15]
128.37914787596716
_____________
9.0914865276836
